apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "raptor.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 4 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 4 }}
    spec:
      serviceAccountName: {{ include "raptor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
