apiVersion: v1
kind: Service
metadata:
  name: {{ include "raptor.fullname" . }}
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
