apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raptor-hello
  template:
    metadata:
      labels:
        app: raptor-hello
    spec:
      containers:
        - name: raptor-hello
          image: superabee/raptor-hello:latest
          imagePullPolicy: Always
