apiVersion: v1
kind: Service
metadata:
  name: raptor-hello
  labels:
    app: raptor-hello
spec:
  selector:
    app: raptor-hello
  type: NodePort
  ports:
  - port: 8878
    targetPort: 8878
    nodePort: 30001
