apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "raptor.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: {{ include "raptor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          imagePullPolicy: IfNotPresent
          env: 
          - name: SERVICE_CENTER
            value: k8s
          - name: CONFIG_CENTER
            value: k8s
