apiVersion: v1
kind: Service
metadata:
  name: {{ include "raptor.fullname" . }}
  labels:
    app: scheduler
spec:
  selector:
    app: scheduler
  type: NodePort
  ports:
  - name: raptor
    port: 1234
    targetPort: 1234
    nodePort: 30002
  - name: prometheus
    port: 8877
    targetPort: 8877
    nodePort: 30000
