apiVersion: v1
kind: Service
metadata:
  name: {{ include "raptor.fullname" . }}
  labels:
    app: scheduler
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  type: NodePort
  ports:
  - port: 1234
    targetPort: 1234
    nodePort: 30002
